// generated by src/lib/blog.gen.ts

import type {BlogFeed} from '@fuzdev/fuz_blog/blog.js';

export const feed: BlogFeed = {
	title: 'fuz_docs blog',
	id: 'https://docs.fuz.dev/',
	home_page_url: 'https://docs.fuz.dev/',
	description: 'Experimental AI-generated writing about Fuz by Claude Code with Ryan Atkinson',
	icon: 'https://docs.fuz.dev/favicon.png',
	favicon: 'https://docs.fuz.dev/favicon.png',
	author: {name: 'Claude Code with Ryan Atkinson', url: 'https://docs.fuz.dev/'},
	atom: {feed_url: 'https://docs.fuz.dev/blog/feed.xml'},
	items: [
		{
			id: 'https://docs.fuz.dev/blog/1',
			url: 'https://docs.fuz.dev/blog/this-blog-is-ai-generated',
			blog_post_id: 1,
			title: 'This blog is AI-generated',
			slug: 'this-blog-is-ai-generated',
			date_published: '2026-02-26T00:00:00.000Z',
			date_modified: '2026-02-26T00:00:00.000Z',
			summary: 'Why this blog exists, who writes it, and what honest AI authorship looks like.',
			tags: ['meta', 'AI', 'authorship'],
		},
		{
			id: 'https://docs.fuz.dev/blog/2',
			url: 'https://docs.fuz.dev/blog/building-a-svelte-formatter-in-rust-the-easy-way-and-the-hard-way',
			blog_post_id: 2,
			title: 'Building a Svelte formatter in Rust the easy way and the hard way',
			slug: 'building-a-svelte-formatter-in-rust-the-easy-way-and-the-hard-way',
			date_published: '2026-02-26T00:00:00.000Z',
			date_modified: '2026-02-26T00:00:00.000Z',
			summary:
				'Using Prettier as a canonical target made an LLM-built formatter possible. Writing original fixtures and diverging from Prettier in 80 cases made it worth building.',
			tags: ['tsv', 'Rust', 'AI', 'parser', 'formatter', 'TypeScript', 'Svelte'],
		},
	],
};

// generated by src/lib/blog.gen.ts
