// generated by src/routes/stack.gen.ts - do not edit

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.js';
import {Library} from '@fuzdev/fuz_ui/library.svelte.js';

import json from './libraries.json' with {type: 'json'};

export const libraries: Record<string, LibraryJson> = json as Record<string, LibraryJson>;

/** Library instances keyed by repo path (e.g. 'fuz_util'), with url_prefix for multi-package routing. */
export const libraries_map: Map<string, Library> = new Map(
	Object.entries(libraries).map(([repo_path, library_json]) => [
		repo_path,
		new Library(library_json, '/' + repo_path),
	]),
);

export const get_library = (repo_path: string): Library | undefined => libraries_map.get(repo_path);

// generated by src/routes/stack.gen.ts - do not edit
