import type {Gen} from '@fuzdev/gro';
import {readFileSync, existsSync} from 'node:fs';
import {execSync} from 'node:child_process';
import {join} from 'node:path';

const DEV_DIR = join(process.env.HOME!, 'dev');

const TYPESCRIPT_REPOS = [
	{path: 'fuz_util', name: '@fuzdev/fuz_util'},
	{path: 'gro', name: '@fuzdev/gro'},
	{path: 'fuz_css', name: '@fuzdev/fuz_css'},
	{path: 'fuz_ui', name: '@fuzdev/fuz_ui'},
	{path: 'fuz_app', name: '@fuzdev/fuz_app'},
	{path: 'fuz_code', name: '@fuzdev/fuz_code'},
	{path: 'fuz_template', name: '@fuzdev/fuz_template'},
	{path: 'fuz_blog', name: '@fuzdev/fuz_blog'},
	{path: 'fuz_mastodon', name: '@fuzdev/fuz_mastodon'},
	{path: 'fuz_gitops', name: '@fuzdev/fuz_gitops'},
	{path: 'fuz_docs', name: '@fuzdev/fuz_docs'},
	{path: 'fuz.dev', name: '@fuzdev/fuz.dev'},
	{path: 'zzz', name: '@fuzdev/zzz'},
];

const RUST_WORKSPACES: Array<{path: string; name: string}> = [{path: 'blake3', name: 'blake3'}];

const read_json = (file_path: string): any => {
	if (!existsSync(file_path)) return null;
	try {
		return JSON.parse(readFileSync(file_path, 'utf-8'));
	} catch {
		return null;
	}
};

const exec_trimmed = (cmd: string): string | null => {
	try {
		return execSync(cmd, {encoding: 'utf-8', timeout: 10_000}).trim();
	} catch {
		return null;
	}
};

export const gen: Gen = ({origin_path}) => {
	const banner = `// generated by ${origin_path} - do not edit`;

	// Toolchain versions
	const toolchain: Record<string, string> = {};

	const rustc = exec_trimmed('rustc --version');
	if (rustc) toolchain.rustc = rustc;

	const cargo = exec_trimmed('cargo --version');
	if (cargo) toolchain.cargo = cargo;

	const node = exec_trimmed('node --version');
	if (node) toolchain.node = node;

	// Read exact installed versions from node_modules
	const node_modules = join(DEV_DIR, 'fuz_docs', 'node_modules');
	const toolchain_packages: Array<[string, string]> = [
		['svelte', 'svelte'],
		['sveltekit', '@sveltejs/kit'],
		['typescript', 'typescript'],
		['gro', '@fuzdev/gro'],
		['prettier', 'prettier'],
		['vitest', 'vitest'],
	];
	for (const [key, pkg_name] of toolchain_packages) {
		const pkg = read_json(join(node_modules, pkg_name, 'package.json'));
		if (pkg?.version) toolchain[key] = pkg.version;
	}

	// Unified libraries array (packages + crates)
	const libraries: Array<Record<string, any>> = [];
	const libraries_by_path: Record<string, any> = {};
	const dependency_graph: Record<string, Array<string>> = {};

	// TypeScript packages
	for (const repo of TYPESCRIPT_REPOS) {
		const repo_dir = join(DEV_DIR, repo.path);
		const pkg_json = read_json(join(repo_dir, 'package.json'));
		if (!pkg_json) continue;

		const library_json = read_json(join(repo_dir, 'src', 'routes', 'library.json'));
		const source_json = library_json?.source_json;
		const modules: Array<{path: string; declarations: Array<{name: string; kind: string}>}> =
			source_json?.modules ?? [];

		const module_count = modules.length;
		let export_count = 0;
		let exported_module_count = 0;

		for (const mod of modules) {
			const declarations = mod.declarations;
			export_count += declarations.length;
			if (declarations.length > 0) {
				exported_module_count++;
			}
		}

		// Include full library.json for repos that have modules
		if (library_json && module_count > 0) {
			libraries_by_path[repo.path] = library_json;
		}

		// Extract @fuzdev deps by category
		const peer_dependencies = Object.keys(pkg_json.peerDependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);
		const runtime_dependencies = Object.keys(pkg_json.dependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);
		const dev_dependencies = Object.keys(pkg_json.devDependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);

		// Runtime graph: peer + runtime deps (excludes dev-only deps)
		dependency_graph[repo.name] = [
			...new Set([...peer_dependencies, ...runtime_dependencies]),
		].sort();

		libraries.push({
			kind: 'package',
			name: repo.name,
			version: pkg_json.version ?? library_json?.package_json?.version ?? '',
			path: repo.path,
			description: pkg_json.description ?? '',
			glyph: pkg_json.glyph ?? '',
			homepage_url: library_json?.homepage_url ?? pkg_json.homepage ?? '',
			published: library_json?.published ?? !pkg_json.private,
			module_count,
			exported_module_count,
			export_count,
			peer_dependencies,
			runtime_dependencies,
			dev_dependencies,
		});
	}

	// Rust workspaces → crate entries
	for (const workspace of RUST_WORKSPACES) {
		const cargo_toml = join(DEV_DIR, workspace.path, 'Cargo.toml');
		if (!existsSync(cargo_toml)) continue;

		const workspace_pkg_json = read_json(join(DEV_DIR, workspace.path, 'package.json'));

		try {
			const metadata_raw = execSync(
				`cargo metadata --manifest-path=${cargo_toml} --format-version=1 --no-deps`,
				{encoding: 'utf-8', timeout: 30_000},
			);
			const metadata = JSON.parse(metadata_raw);
			const workspace_names = new Set((metadata.packages ?? []).map((p: {name: string}) => p.name));
			const edition = (metadata.packages as Array<{edition?: string}>)[0]?.edition ?? '';

			for (const pkg of metadata.packages ?? []) {
				const crate_kind = pkg.targets?.[0]?.kind[0] ?? 'lib';
				const internal_deps = (pkg.dependencies ?? [])
					.filter((d: {name: string}) => workspace_names.has(d.name))
					.map((d: {name: string}) => d.name);

				libraries.push({
					kind: 'crate',
					name: pkg.name,
					version: pkg.version,
					path: workspace.path,
					description: pkg.description ?? '',
					crate_kind,
					edition,
					workspace: workspace.name,
					internal_deps,
				});
			}

			// Include workspace in libraries.json with minimal LibraryJson
			if (workspace_pkg_json) {
				libraries_by_path[workspace.path] = {
					name: workspace_pkg_json.name ?? workspace.name,
					repo_name: workspace.path,
					repo_url: `https://github.com/fuzdev/${workspace.path}`,
					owner_name: 'fuzdev',
					homepage_url: null,
					logo_url: null,
					logo_alt: '',
					npm_url: null,
					changelog_url: null,
					published: false,
					package_json: workspace_pkg_json,
					source_json: {
						name: workspace_pkg_json.name ?? workspace.name,
						version: workspace_pkg_json.version ?? '0.0.1',
						modules: [],
					},
				};
			}
		} catch {
			// Skip workspaces where cargo metadata fails
		}
	}

	const stack_data = {
		toolchain,
		libraries,
		dependency_graph,
	};

	const stack_json = JSON.stringify(stack_data, null, '\t');
	const libraries_json = JSON.stringify(libraries_by_path, null, '\t');

	const stack_ts = `${banner}

import stack_data from './stack.json' with {type: 'json'};

export const stack = stack_data;

${banner}
`;

	const libraries_ts = `${banner}

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.js';
import {Library} from '@fuzdev/fuz_ui/library.svelte.js';

import json from './libraries.json' with {type: 'json'};

export const libraries: Record<string, LibraryJson> = json as Record<string, LibraryJson>;

/** Library instances keyed by repo path (e.g. 'fuz_util'), with url_prefix for multi-package routing. */
export const libraries_map: Map<string, Library> = new Map(
\tObject.entries(libraries).map(([repo_path, library_json]) => [
\t\trepo_path,
\t\tnew Library(library_json, '/' + repo_path),
\t]),
);

export const get_library = (repo_path: string): Library | undefined =>
\tlibraries_map.get(repo_path);

${banner}
`;

	return [
		{content: stack_json, filename: 'stack.json'},
		{content: libraries_json, filename: 'libraries.json'},
		{content: stack_ts, filename: 'stack.ts'},
		{content: libraries_ts, filename: 'libraries.ts'},
	];
};
