// generated by src/routes/stack.gen.ts - do not edit

import stack_data from './stack.json' with {type: 'json'};

export const stack = stack_data;

// generated by src/routes/stack.gen.ts - do not edit
