import type {Gen} from '@fuzdev/gro';
import {library_load_from_repo} from '@fuzdev/gro/library_load.ts';
import type {LibraryJson} from '@fuzdev/fuz_util/library_json.ts';
import {package_is_published} from '@fuzdev/fuz_util/package_helpers.ts';
import {pkg_json_from_package_json} from '@fuzdev/fuz_util/pkg_json.ts';
import {compactReplacer} from 'svelte-docinfo/declaration-helpers.js';
import {readFileSync, existsSync} from 'node:fs';
import {execSync} from 'node:child_process';
import {join} from 'node:path';

import {stack_repos} from '$lib/stack_repos.ts';

const DEV_DIR = join(process.env.HOME!, 'dev');

// Derived from the shared `stack_repos` list: `ts` repos are analyzed with
// svelte-docinfo via gro's loader; `wasm`/`rust` repos are read via `cargo metadata`.
const TYPESCRIPT_REPOS = stack_repos.filter((repo) => repo.language === 'ts');
const RUST_WORKSPACES = stack_repos.filter((repo) => repo.language !== 'ts');

const read_json = (file_path: string): any => {
	if (!existsSync(file_path)) return null;
	try {
		return JSON.parse(readFileSync(file_path, 'utf-8'));
	} catch {
		return null;
	}
};

const exec_trimmed = (cmd: string): string | null => {
	try {
		return execSync(cmd, {encoding: 'utf-8', timeout: 10_000}).trim();
	} catch {
		return null;
	}
};

export const gen: Gen = async ({origin_path, log}) => {
	const banner = `// generated by ${origin_path} - do not edit`;

	// Toolchain versions
	const toolchain: Record<string, string> = {};

	const rustc = exec_trimmed('rustc --version');
	if (rustc) toolchain.rustc = rustc;

	const cargo = exec_trimmed('cargo --version');
	if (cargo) toolchain.cargo = cargo;

	const node = exec_trimmed('node --version');
	if (node) toolchain.node = node;

	// Read exact installed versions from node_modules
	const node_modules = join(DEV_DIR, 'fuz_docs', 'node_modules');
	const toolchain_packages: Array<[string, string]> = [
		['svelte', 'svelte'],
		['sveltekit', '@sveltejs/kit'],
		['typescript', 'typescript'],
		['gro', '@fuzdev/gro'],
		['prettier', 'prettier'],
		['vitest', 'vitest'],
	];
	for (const [key, pkg_name] of toolchain_packages) {
		const pkg = read_json(join(node_modules, pkg_name, 'package.json'));
		if (pkg?.version) toolchain[key] = pkg.version;
	}

	// Unified libraries array (packages + crates)
	const libraries: Array<Record<string, any>> = [];
	const libraries_by_path: Record<string, LibraryJson> = {};
	const dependency_graph: Record<string, Array<string>> = {};

	// TypeScript packages
	for (const repo of TYPESCRIPT_REPOS) {
		const repo_dir = join(DEV_DIR, repo.path);
		const pkg_json = read_json(join(repo_dir, 'package.json'));
		if (!pkg_json) continue;

		let library_json = null;
		try {
			({library_json} = await library_load_from_repo(repo_dir, {log}));
		} catch (err) {
			log.warn(`skipping ${repo.name}: failed to analyze ${repo_dir}`, err);
		}
		const source_json = library_json?.source_json;
		const modules = source_json?.modules ?? [];

		const module_count = modules.length;
		let export_count = 0;
		let exported_module_count = 0;

		for (const mod of modules) {
			const declarations = mod.declarations ?? [];
			export_count += declarations.length;
			if (declarations.length > 0) {
				exported_module_count++;
			}
		}

		// Include full library.json for repos that have modules
		if (library_json && module_count > 0) {
			libraries_by_path[repo.path] = library_json;
		}

		// Extract @fuzdev deps by category
		const peer_dependencies = Object.keys(pkg_json.peerDependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);
		const runtime_dependencies = Object.keys(pkg_json.dependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);
		const dev_dependencies = Object.keys(pkg_json.devDependencies ?? {}).filter(
			(dep) => dep.startsWith('@fuzdev/') && dep !== repo.name,
		);

		// Runtime graph: peer + runtime deps (excludes dev-only deps)
		dependency_graph[repo.name] = [
			...new Set([...peer_dependencies, ...runtime_dependencies]),
		].sort();

		libraries.push({
			kind: 'package',
			name: repo.name,
			version: pkg_json.version ?? '',
			path: repo.path,
			description: pkg_json.description ?? '',
			glyph: pkg_json.glyph ?? '',
			homepage_url: pkg_json.homepage ?? '',
			published: package_is_published(pkg_json),
			module_count,
			exported_module_count,
			export_count,
			peer_dependencies,
			runtime_dependencies,
			dev_dependencies,
		});
	}

	// Rust workspaces → crate entries
	for (const workspace of RUST_WORKSPACES) {
		const cargo_toml = join(DEV_DIR, workspace.path, 'Cargo.toml');
		if (!existsSync(cargo_toml)) continue;

		const workspace_pkg_json = read_json(join(DEV_DIR, workspace.path, 'package.json'));

		try {
			const metadata_raw = execSync(
				`cargo metadata --manifest-path=${cargo_toml} --format-version=1 --no-deps`,
				{encoding: 'utf-8', timeout: 30_000},
			);
			const metadata = JSON.parse(metadata_raw);
			const workspace_names = new Set((metadata.packages ?? []).map((p: {name: string}) => p.name));
			const edition = (metadata.packages as Array<{edition?: string}>)[0]?.edition ?? '';

			for (const pkg of metadata.packages ?? []) {
				const crate_kind = pkg.targets?.[0]?.kind[0] ?? 'lib';
				const internal_deps = (pkg.dependencies ?? [])
					.filter((d: {name: string}) => workspace_names.has(d.name))
					.map((d: {name: string}) => d.name);

				libraries.push({
					kind: 'crate',
					name: pkg.name,
					version: pkg.version,
					path: workspace.path,
					description: pkg.description ?? '',
					crate_kind,
					edition,
					workspace: workspace.path,
					internal_deps,
				});
			}

			// Include workspace in libraries.json with a minimal LibraryJson. Inject
			// `name`/`repository` so `Library` can derive its identity (repo url, etc.),
			// then curate to the publish-safe `PkgJson` so the full Cargo-side
			// `package.json` (scripts, deps, …) never rides along into the client.
			if (workspace_pkg_json) {
				libraries_by_path[workspace.path] = {
					pkg_json: pkg_json_from_package_json({
						...workspace_pkg_json,
						name: workspace_pkg_json.name ?? workspace.path,
						repository: `https://github.com/fuzdev/${workspace.path}`,
					}),
					source_json: {modules: []},
				};
			}
		} catch {
			// Skip workspaces where cargo metadata fails
		}
	}

	const stack_data = {
		toolchain,
		libraries,
		dependency_graph,
	};

	const stack_json = JSON.stringify(stack_data, null, '\t');
	// Serialize through `compactReplacer` so the baked `modules` match svelte-docinfo's
	// wire shape (the input side emitted by `virtual:svelte-docinfo`): empty arrays and
	// `false` are dropped, restored by Zod defaults on parse. Shrinks the file and keeps
	// both producers shape-aligned. gro's loader hands back the fuller output side.
	const libraries_json = JSON.stringify(libraries_by_path, compactReplacer, '\t');

	const stack_ts = `${banner}

import stack_data from './stack.json' with {type: 'json'};

export const stack = stack_data;

${banner}
`;

	const libraries_ts = `${banner}

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.ts';
import {Library} from '@fuzdev/fuz_ui/library.svelte.ts';

import json from './libraries.json' with {type: 'json'};

export const libraries: Record<string, LibraryJson> = json as Record<string, LibraryJson>;

/** Library instances keyed by repo path (e.g. 'fuz_util'), with url_prefix for multi-package routing. */
export const libraries_map: Map<string, Library> = new Map(
\tObject.entries(libraries).map(([repo_path, library_json]) => [
\t\trepo_path,
\t\tnew Library(library_json, '/' + repo_path),
\t]),
);

export const get_library = (repo_path: string): Library | undefined =>
\tlibraries_map.get(repo_path);

${banner}
`;

	return [
		{content: stack_json, filename: 'stack.json'},
		{content: libraries_json, filename: 'libraries.json'},
		{content: stack_ts, filename: 'stack.ts'},
		{content: libraries_ts, filename: 'libraries.ts'},
	];
};
