<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import Mdz from '@fuzdev/mdz/Mdz.svelte';
	import MdzRoot from '@fuzdev/mdz/MdzRoot.svelte';
	import Code from '@fuzdev/fuz_code/Code.svelte';

	import { skill_references } from '../../skill_data.ts';
</script>

<MdzRoot codeblock={Code}>
	<Mdz content={skill_references[0]!.content} base="/skills/fuz-stack/references/" />
</MdzRoot>

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
