<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import Mdz from '@fuzdev/mdz/Mdz.svelte';

	import {skill_references} from '../../skill_data.ts';
</script>

<Mdz content={skill_references[0]!.content} base="/skills/fuz-stack/references/" />

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
