<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import Mdz from '@fuzdev/fuz_ui/Mdz.svelte';

	import {skill_main} from './skill_data.js';
</script>

<Mdz content={skill_main.content} base="/skills/grimoire/" />

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
