<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import {resolve} from '$app/paths';

	import {skills} from '$routes/skills/skills_manifest.ts';

	const skill = skills.find((s) => s.name === 'fuz-stack')!;
</script>

<h1>References</h1>
<ul>
	{#each skill.references as ref (ref.slug)}
		<li>
			<a href={resolve(('/skills/fuz-stack/references/' + ref.slug) as any)}>{ref.title}</a>
			— {ref.description}
		</li>
	{/each}
</ul>

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
