<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import {resolve} from '$app/paths';

	import {skill_references} from '../skill_data.js';
</script>

<h1>References</h1>
<ul>
	{#each skill_references as ref (ref.slug)}
		<li><a href={resolve(('/skills/fuz-stack/references/' + ref.slug) as any)}>{ref.title}</a></li>
	{/each}
</ul>

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
