// generated by src/routes/skills/skill_docs.gen.ts - do not edit

export interface Skill_Meta {
	name: string;
	title: string;
	description: string;
	references: Array<{slug: string; title: string}>;
}

export const skills: Array<Skill_Meta> = [
	{
		name: 'fuz-stack',
		title: 'Fuz stack conventions',
		description:
			'Development conventions and coding patterns for the @fuzdev ecosystem — naming, file organization, testing, styling, documentation, and tooling for TypeScript and Svelte 5 projects. Use when writing or reviewing code in any @fuzdev project. Triggers include running gro commands (gro check, gro test, gro gen), styling with fuz_css, writing or splitting tests, generating code with .gen.ts files, naming functions or variables (snake_case conventions), organizing files in src/lib/ or src/test/, writing TSDoc comments, creating Svelte 5 components with runes, or formatting code. Also use for the Result type, fixture-based testing, CSS utility classes, TODO_ docs, breaking changes policy, async concurrency patterns, Gro task system, type utilities (Flavored, Branded), dependency injection patterns (*Deps/*Options/*Context interfaces, AppDeps, RuntimeDeps, mock factories), or setting up documentation (tomes, library.gen.ts, API routes, docs layout).',
		references: [
			{slug: 'async-patterns', title: 'Async Patterns'},
			{slug: 'code-generation', title: 'Code Generation'},
			{slug: 'common-utilities', title: 'Common Utilities'},
			{slug: 'css-patterns', title: 'CSS Patterns'},
			{slug: 'dependency-injection', title: 'Dependency Injection'},
			{slug: 'documentation-system', title: 'Documentation System'},
			{slug: 'rust-conventions', title: 'Rust Conventions for the Fuz Ecosystem'},
			{slug: 'svelte-patterns', title: 'Svelte 5 Patterns'},
			{slug: 'task-patterns', title: 'Task Patterns'},
			{slug: 'testing-patterns', title: 'Testing Patterns'},
			{slug: 'tsdoc-comments', title: 'TSDoc Comment Style Guide'},
			{slug: 'type-utilities', title: 'Type Utilities'},
			{slug: 'wasm-patterns', title: 'WASM Patterns for the Fuz Ecosystem'},
			{slug: 'zod-schemas', title: 'Zod Schemas'},
		],
	},
	{
		name: 'grimoire',
		title: 'Grimoire',
		description:
			'Navigate and maintain a grimoire — a markdown meta-repo that coordinates work across multiple sibling repositories. Covers the three primitives: skills (agent knowledge files), lore (per-repo planning projections), and quests (cross-repo goals). Use when orienting work across repos, reading project planning context, checking TODOs before working on a project, updating planning docs after completing work, creating or updating lore entries, drafting new quests, deciding whether to create a quest vs a lore TODO, pruning stale decisions from lore entries, or understanding grimoire conventions and structure.',
		references: [],
	},
];

// generated by src/routes/skills/skill_docs.gen.ts - do not edit
