import type {Gen} from '@fuzdev/gro/gen.js';
import {readFileSync, readdirSync, existsSync} from 'node:fs';
import {join, basename} from 'node:path';

const SKILLS_DIR = join(process.cwd(), 'skills');

const parse_frontmatter = (raw: string): {content: string; frontmatter: Record<string, string>} => {
	const frontmatter: Record<string, string> = {};
	if (!raw.startsWith('---')) return {content: raw, frontmatter};
	const end = raw.indexOf('---', 3);
	if (end === -1) return {content: raw, frontmatter};
	const yaml_block = raw.slice(3, end).trim();
	for (const line of yaml_block.split('\n')) {
		const colon = line.indexOf(':');
		if (colon === -1) continue;
		const key = line.slice(0, colon).trim();
		const value = line.slice(colon + 1).trim();
		if (key && value && !key.startsWith(' ')) {
			frontmatter[key] = value;
		}
	}
	return {content: raw.slice(end + 3).trimStart(), frontmatter};
};

const HEADING_RE = /^#\s+(.+)$/m;

const extract_title = (content: string): string => {
	const match = HEADING_RE.exec(content);
	return match?.[1]?.trim() ?? 'Untitled';
};

const to_slug = (filename: string): string => basename(filename, '.md').replaceAll('_', '-');

/**
 * Strips `.md` extensions from bare relative paths for web route resolution.
 * ./foo.md → ./foo, ./references/foo.md → ./references/foo
 * Skips fenced code blocks and backtick-wrapped paths.
 */
const rewrite_md_links = (content: string): string => {
	const lines = content.split('\n');
	let in_code_block = false;

	for (let i = 0; i < lines.length; i++) {
		const trimmed = lines[i]!.trimStart();

		// Track fenced code blocks — don't rewrite inside them
		if (!in_code_block && trimmed.startsWith('```')) {
			in_code_block = true;
		} else if (in_code_block && trimmed.startsWith('```')) {
			in_code_block = false;
			continue;
		}

		if (!in_code_block) {
			lines[i] = lines[i]!.replace(/(?<!`)(\.\/[\w/-]+)\.md(?!`)/g, '$1');
		}
	}

	return lines.join('\n');
};

export const gen: Gen = ({origin_path}) => {
	const banner = `// generated by ${origin_path} - do not edit`;
	const svelte_banner = `<!-- generated by ${origin_path} -->`;
	const skills_route_dir = join(process.cwd(), 'src/routes/skills');

	// auto-discover skills
	const skill_dirs = readdirSync(SKILLS_DIR, {withFileTypes: true})
		.filter((d) => d.isDirectory() && existsSync(join(SKILLS_DIR, d.name, 'SKILL.md')))
		.map((d) => d.name)
		.sort();

	const skills_meta: Array<{
		name: string;
		title: string;
		description: string;
		references: Array<{slug: string; title: string}>;
	}> = [];

	const output_files: Array<{content: string; filename: string}> = [];

	for (const skill_name of skill_dirs) {
		const skill_dir = join(SKILLS_DIR, skill_name);
		const skill_route_dir = join(skills_route_dir, skill_name);

		// read SKILL.md
		const skill_raw = readFileSync(join(skill_dir, 'SKILL.md'), 'utf-8');
		const {content: skill_content, frontmatter} = parse_frontmatter(skill_raw);
		const skill_title = extract_title(skill_content);
		const skill_description = frontmatter.description ?? '';

		// read references if directory exists
		const refs_dir = join(skill_dir, 'references');
		const has_refs = existsSync(refs_dir);
		const references: Array<{slug: string; title: string; content: string}> = [];

		if (has_refs) {
			const ref_files = readdirSync(refs_dir)
				.filter((f) => f.endsWith('.md'))
				.sort();
			for (const filename of ref_files) {
				const raw_content = readFileSync(join(refs_dir, filename), 'utf-8');
				const title = extract_title(raw_content);
				const slug = to_slug(filename);
				const content = rewrite_md_links(raw_content);
				references.push({slug, title, content});
			}
		}

		// collect metadata for manifest
		skills_meta.push({
			name: skill_name,
			title: skill_title,
			description: skill_description,
			references: references.map((r) => ({slug: r.slug, title: r.title})),
		});

		// generate per-skill skill_data.ts
		output_files.push({
			content: `${banner}

export interface Skill_Doc {
	slug: string;
	title: string;
	content: string;
}

export const skill_main: Skill_Doc = ${JSON.stringify({slug: 'overview', title: skill_title, content: rewrite_md_links(skill_content)})};

export const skill_references: Array<Skill_Doc> = ${JSON.stringify(references)};

${banner}
`,
			filename: join(skill_route_dir, 'skill_data.ts'),
		});

		// generate skill index +page.svelte
		output_files.push({
			content: `${svelte_banner}

<script lang="ts">
	import Mdz from '@fuzdev/fuz_ui/Mdz.svelte';

	import {skill_main} from './skill_data.js';
</script>

<Mdz content={skill_main.content} base="/skills/${skill_name}/" />

${svelte_banner}
`,
			filename: join(skill_route_dir, '+page.svelte'),
		});

		// generate references index +page.svelte
		if (references.length > 0) {
			output_files.push({
				content: `${svelte_banner}

<script lang="ts">
	import {resolve} from '$app/paths';

	import {skill_references} from '../skill_data.js';
</script>

<h1>References</h1>
<ul>
	{#each skill_references as ref (ref.slug)}
		<li><a href={resolve(('/skills/${skill_name}/references/' + ref.slug) as any)}>{ref.title}</a></li>
	{/each}
</ul>

${svelte_banner}
`,
				filename: join(skill_route_dir, 'references', '+page.svelte'),
			});
		}

		// generate per-reference +page.svelte files
		for (let i = 0; i < references.length; i++) {
			const ref = references[i]!;
			output_files.push({
				content: `${svelte_banner}

<script lang="ts">
	import Mdz from '@fuzdev/fuz_ui/Mdz.svelte';

	import {skill_references} from '../../skill_data.js';
</script>

<Mdz content={skill_references[${i}]!.content} base="/skills/${skill_name}/references/" />

${svelte_banner}
`,
				filename: join(skill_route_dir, 'references', ref.slug, '+page.svelte'),
			});
		}
	}

	// generate skills_manifest.ts
	const manifest_content = `${banner}

export interface Skill_Meta {
	name: string;
	title: string;
	description: string;
	references: Array<{slug: string; title: string}>;
}

export const skills: Array<Skill_Meta> = ${JSON.stringify(skills_meta)};

${banner}
`;

	return [{content: manifest_content, filename: 'skills_manifest.ts'}, ...output_files];
};
