<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import Mdz from '@fuzdev/mdz/Mdz.svelte';
	import MdzRoot from '@fuzdev/mdz/MdzRoot.svelte';
	import Code from '@fuzdev/fuz_code/Code.svelte';

	import {skill_main} from './skill_data.ts';
</script>

<MdzRoot codeblock={Code}>
	<Mdz content={skill_main.content} base="/skills/fuz-stack/" />
</MdzRoot>

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
