import type {Gen} from '@fuzdev/gro/gen.ts';
import {readFileSync, existsSync} from 'node:fs';
import {join} from 'node:path';

import {compute_stack_layout, type StackNodeInput} from '$lib/stack_layout.ts';
import type {
	StackCategory,
	StackEdge,
	StackEdgeKind,
	StackLanguage,
} from '$lib/stack_graph_types.ts';
import {stack_repos} from '$lib/stack_repos.ts';

// Sibling repos live one level up from the fuz_docs repo root (the gen runs from
// the repo root, so `process.cwd()` is the fuz_docs repo root and the workspace is its parent).
const DEV_DIR = join(process.cwd(), '..');

/**
 * Known package-name aliases that resolve to a repo dir but differ from that
 * repo's manifest `name`. The blake3 repo's manifest is named `@fuzdev/blake3`
 * but it publishes the `@fuzdev/blake3_wasm` / `@fuzdev/blake3_wasm_small`
 * packages that consumers actually depend on.
 */
const PACKAGE_NAME_ALIASES: Record<string, string> = {
	'@fuzdev/blake3_wasm': 'blake3',
	'@fuzdev/blake3_wasm_small': 'blake3',
};

interface ManifestInfo {
	dir: string;
	/** Package name from the manifest, e.g. `@fuzdev/fuz_util`. */
	name: string;
	description: string;
	/** Editorial category, carried from the shared `stack_repos` list. */
	category: StackCategory;
	language: StackLanguage;
	/** Raw dependency names by edge kind, before allowlist resolution. */
	deps: Array<{name: string; kind: StackEdgeKind}>;
}

const read_json = (file_path: string): any => {
	try {
		return JSON.parse(readFileSync(file_path, 'utf-8'));
	} catch {
		return null;
	}
};

/**
 * Minimal `Cargo.toml` reader for future public Rust repos. Extracts the
 * package `name` and `description` from the `[package]` table. Not a full TOML
 * parser — only the fields we need, good enough for the manifest shape. Exists
 * so the generator is ready when a public Rust repo joins `stack_repos`; today
 * no allowlisted repo lacks a `package.json`, so it stays unexercised in practice.
 */
const read_cargo_toml = (file_path: string): {name: string; description: string} | null => {
	let raw;
	try {
		raw = readFileSync(file_path, 'utf-8');
	} catch {
		return null;
	}
	const lines = raw.split('\n');
	let in_package = false;
	let name = '';
	let description = '';
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed.startsWith('[')) {
			in_package = trimmed === '[package]';
			continue;
		}
		if (!in_package) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		const value = trimmed
			.slice(eq + 1)
			.trim()
			.replace(/^["']|["']$/g, '');
		if (key === 'name') name = value;
		else if (key === 'description') description = value;
	}
	if (!name) return null;
	return {name, description};
};

const fuzdev_dep_names = (block: Record<string, unknown> | undefined): Array<string> =>
	Object.keys(block ?? {});

const STRENGTH: Record<StackEdgeKind, number> = {prod: 3, peer: 2, dev: 1};

export const gen: Gen = ({origin_path, log}) => {
	const banner = `// generated by ${origin_path} - do not edit`;

	// 1/2. read each allowlisted repo's manifest
	const manifests: Array<ManifestInfo> = [];
	for (const repo of stack_repos) {
		const {path: dir, category, language} = repo;
		const repo_dir = join(DEV_DIR, dir);
		if (!existsSync(repo_dir)) {
			log.warn(`stack_graph: repo dir missing, skipping: ${repo_dir}`);
			continue;
		}

		const pkg_path = join(repo_dir, 'package.json');
		const cargo_path = join(repo_dir, 'Cargo.toml');

		if (existsSync(pkg_path)) {
			const pkg = read_json(pkg_path);
			if (!pkg) {
				log.warn(`stack_graph: failed to parse package.json, skipping: ${pkg_path}`);
				continue;
			}
			const deps: Array<{name: string; kind: StackEdgeKind}> = [];
			for (const name of fuzdev_dep_names(pkg.dependencies)) deps.push({name, kind: 'prod'});
			for (const name of fuzdev_dep_names(pkg.peerDependencies)) deps.push({name, kind: 'peer'});
			for (const name of fuzdev_dep_names(pkg.devDependencies)) deps.push({name, kind: 'dev'});
			manifests.push({
				dir,
				name: pkg.name ?? dir,
				description: pkg.description ?? '',
				category,
				language,
				deps,
			});
		} else if (existsSync(cargo_path)) {
			// Rust-only repo: read Cargo.toml (no JS dep graph available here).
			const cargo = read_cargo_toml(cargo_path);
			if (!cargo) {
				log.warn(`stack_graph: failed to parse Cargo.toml, skipping: ${cargo_path}`);
				continue;
			}
			manifests.push({
				dir,
				name: cargo.name,
				description: cargo.description,
				category,
				language,
				deps: [],
			});
		} else {
			log.warn(`stack_graph: no manifest found, skipping: ${repo_dir}`);
		}
	}

	const allow = new Set(manifests.map((m) => m.dir));

	// 3. package-name -> dir map across resolved repos, plus known aliases
	const name_to_dir = new Map<string, string>();
	for (const m of manifests) name_to_dir.set(m.name, m.dir);
	for (const [alias, dir] of Object.entries(PACKAGE_NAME_ALIASES)) {
		if (allow.has(dir)) name_to_dir.set(alias, dir);
	}

	// resolve + de-dupe edges, preferring the strongest kind for a given pair
	const edge_map = new Map<string, StackEdge>();
	for (const m of manifests) {
		for (const dep of m.deps) {
			const to = name_to_dir.get(dep.name);
			// drop deps whose target isn't in the allowlist (closed graph, privacy)
			if (!to || !allow.has(to) || to === m.dir) continue;
			const key = m.dir + '\0' + to;
			const existing = edge_map.get(key);
			if (!existing || STRENGTH[dep.kind] > STRENGTH[existing.kind]) {
				edge_map.set(key, {from: m.dir, to, kind: dep.kind});
			}
		}
	}
	const edges = [...edge_map.values()];

	// 4. raw nodes
	const raw_nodes: Array<StackNodeInput> = manifests.map((m) => ({
		name: m.dir,
		category: m.category,
		language: m.language,
		description: m.description,
	}));

	// 5. positioned nodes via the pure layout
	const positioned = compute_stack_layout(raw_nodes, edges);

	// deterministic ordering for a stable generated file
	const sorted_nodes = [...positioned].sort((a, b) => a.name.localeCompare(b.name));
	const sorted_edges = [...edges].sort(
		(a, b) =>
			a.from.localeCompare(b.from) || a.to.localeCompare(b.to) || a.kind.localeCompare(b.kind),
	);

	const content = `${banner}

export type {
	StackNode,
	StackEdge,
	StackCategory,
	StackLanguage,
	StackEdgeKind,
} from '$lib/stack_graph_types.ts';

import type {StackNode, StackEdge} from '$lib/stack_graph_types.ts';

/** All public stack repos as positioned graph nodes, sorted by name. */
export const stack_nodes: Array<StackNode> = ${JSON.stringify(sorted_nodes, null, '\t')};

/** Every dependency edge (including \`dev\`), sorted by from, then to, then kind. */
export const stack_edges: Array<StackEdge> = ${JSON.stringify(sorted_edges, null, '\t')};

${banner}
`;

	return content;
};
