<!-- generated by src/routes/skills/skill_docs.gen.ts -->

<script lang="ts">
	import Mdz from '@fuzdev/fuz_ui/Mdz.svelte';

	import {skill_references} from '../../skill_data.js';
</script>

<Mdz content={skill_references[9]!.content} base="/skills/fuz-stack/references/" />

<!-- generated by src/routes/skills/skill_docs.gen.ts -->
